FROM java:8
VOLUME /tmp
ADD ./target/springbootdocker-0.0.1.jar springbootapp.jar


RUN bash -c 'touch /springbootapp.jar'

ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/springbootapp.jar"]
